test:
	./test.sh

orig:
	cd orig && node app.js

domains_wrong:
	cd domains_wrong && node app.js

domains:
	cd domains && node app.js

cluster:
	cd cluster && node app.js

cluster_and_domains:
	cd cluster_and_domains && node app.js

longjohn:
	cd longjohn && node app.js

.PHONY: orig domains_wrong domains cluster cluster_and_domains longjohn
	
